server:
  port: <port>
spring:
  datasource:
    url: jdbc:mysql://<domain>:<port>/shopapp?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: <username>
    password: <password>
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  messages:
    basename: i18n/messages
    encoding: UTF-8
    default-locale: en
  # Cấu hình Spring Cache
  cache:
    type: redis # Báo Spring Boot dùng Redis làm cache provider
    redis:
      time-to-live: 600000 # Thời gian sống mặc định của cache (ví dụ: 10 phút)

  kafka:
    bootstrap-servers: localhost:9092 # Địa chỉ Kafka broker
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: shopapp-group # Tên group consumer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trust.packages: "*" # Cho phép deserialize mọi class (hoặc chỉ định cụ thể)
  mail:
    host: smtp.gmail.com
    port: 587
    username: <email>
    # TUYỆT ĐỐI KHÔNG HARDCODE MẬT KHẨU Ở ĐÂY
    # Sử dụng biến môi trường: ${GMAIL_APP_PASSWORD}
    password: <GMAIL_APP_PASSWORD>
    properties:
      mail:
        smtp:
          auth: true
          # Yêu cầu STARTTLS (kết nối an toàn)
          starttls:
            enable: true
  data:
    redis:
      host: <domain>
      port: <port>
api:
  prefix: api/v1
jwt:
  expiration: 2592000
  secretKey: <key>
